"""empty message

Revision ID: 2f3d27b5cf6b
Revises: cbf115b5bc78
Create Date: 2024-07-31 08:54:41.367863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3d27b5cf6b'
down_revision = 'cbf115b5bc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_autor', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.drop_column('imagen_autor')

    # ### end Alembic commands ###
