"""empty message

Revision ID: 884b4d933050
Revises: 
Create Date: 2024-07-30 07:37:15.394364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884b4d933050'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
