"""empty message

Revision ID: 92de3a0a4f17
Revises: 9c245bd92661
Create Date: 2024-08-06 10:28:00.850953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92de3a0a4f17'
down_revision = '9c245bd92661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.drop_column('descripcion_libro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion_libro', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
