"""empty message

Revision ID: 9c245bd92661
Revises: 2f3d27b5cf6b
Create Date: 2024-08-06 10:01:04.229160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c245bd92661'
down_revision = '2f3d27b5cf6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion_libro', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.drop_column('descripcion_libro')

    # ### end Alembic commands ###
