"""empty message

Revision ID: 9cad6afff70b
Revises: bf2ca4556070
Create Date: 2024-07-17 13:34:05.445142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cad6afff70b'
down_revision = 'bf2ca4556070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('user_usaurio_key', type_='unique')
        batch_op.create_unique_constraint(None, ['usuario'])
        batch_op.drop_column('usaurio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usaurio', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_usaurio_key', ['usaurio'])
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###
