"""empty message

Revision ID: cbf115b5bc78
Revises: 884b4d933050
Create Date: 2024-07-30 10:47:10.585450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf115b5bc78'
down_revision = '884b4d933050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###
